ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';
create tablespace Med_Center
datafile 'C:\database_labs\Medical_Center\Med_Cent.dbf'
size 300m
autoextend on next 10m
maxsize 600m
extent management local;

ALTER TABLESPACE Med_Center
ADD DATAFILE 'C:\database_labs\Medical_Center\Med_Cent2.dbf'
SIZE 400M; 

DROP TABLE HOME_ANALYSES;
DROP TABLE WORKDAY;
DROP TABLE ANALYSES;
DROP TABLE DESIASE;
DROP TABLE HEALTH;
DROP TABLE DOCTOR;
DROP TABLE USER_;

CREATE TABLE CREATOR.USER_(
                    ID_USER NUMBER(6, 0) PRIMARY KEY NOT NULL,
                    FULLNAME NVARCHAR2(50) NOT NULL,--маскируем
                    BIRTH_DATE DATE NOT NULL,--маскируем
                    EMAIL NVARCHAR2(100) NOT NULL UNIQUE,--маскируем
                    LOGIN VARCHAR2(100) NOT NULL UNIQUE,--aes128
                    PASSWORD VARCHAR2(64) NOT NULL--aes192
                    ) tablespace Med_Center;


CREATE TABLE CREATOR.HOME_ANALYSES(
                            ID_ANALYSES NUMBER (10, 0) PRIMARY KEY NOT NULL,
                            ID_USER NUMBER(6,0) NOT NULL,
                            PULSE VARCHAR2 (32) NULL, --encrypt_des
                            TEMPERATURE VARCHAR2(32) NULL,--encrypt_des
                            BLOOD_PRESS VARCHAR2(32) NULL,--aes_192
                            DATE_ANALYSE TIMESTAMP,--маскируем
                            CONSTRAINT FK_ID_USER FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER) 
                            ) tablespace Med_Center;

CREATE TABLE CREATOR.DOCTOR(
                    ID_DOCTOR NUMBER(6, 0) PRIMARY KEY NOT NULL,
                    FULL_NAME NVARCHAR2(50) NOT NULL, -- маскируем
                    SPECIALITY NVARCHAR2(45) NOT NULL,
                    EMAIL NVARCHAR2(100) NULL UNIQUE, -- маскируем
                    LOGIN VARCHAR2(64) NOT NULL UNIQUE, -- aes_128
                    PASSWORD VARCHAR2(64) NOT NULL --aes_128
                    ) tablespace Med_Center;


CREATE TABLE CREATOR.WORKDAY(
                     ID_WORKDAY NUMBER (10, 0) PRIMARY KEY NOT NULL,
                     ID_DOCTOR NUMBER(6,0) NOT NULL,
                     CABINET NUMBER(4,0) NOT NULL,
                     BEGINING TIMESTAMP(0),
                     ENDING TIMESTAMP(0),
                     CONSTRAINT PK_WORKDAY FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR)
                    ) TABLESPACE MED_CENTER;
                    

CREATE TABLE CREATOR.HEALTH(
                     ID_VISITE NUMBER (15, 0) PRIMARY KEY NOT NULL,
                     ID_USER NUMBER(6,0) NOT NULL,
                     ID_DOCTOR NUMBER(6,0) NOT NULL,
                     DATE_TIME_VISITE TIMESTAMP NOT NULL, --маскируем
                     CONSTRAINT FK_DOCTOR FOREIGN KEY (ID_DOCTOR) REFERENCES DOCTOR(ID_DOCTOR),
                     CONSTRAINT FK_USER FOREIGN KEY (ID_USER) REFERENCES USER_(ID_USER)
                     ) TABLESPACE MED_CENTER;


CREATE TABLE CREATOR.ANALYSES(
                     ID_ANALYSE NUMBER(15, 0) PRIMARY KEY NOT NULL,
                     ID_VISITE NUMBER (15, 0) NOT NULL,
                     LABARATORY VARCHAR2(5) NOT NULL,
                     NAME_ANALYSE NVARCHAR2(50) NOT NULL, --маскировка
                     RESULT_ANALYSE NVARCHAR2(100) NULL, --маскировка
                     DATE_TIME_ANALYSE TIMESTAMP NOT NULL, --маскируем
                     CONSTRAINT FK_VISITE FOREIGN KEY (ID_VISITE) REFERENCES HEALTH(ID_VISITE)
                     ) TABLESPACE MED_CENTER;

CREATE TABLE CREATOR.DESIASE(
                        ID_DESIASE NUMBER(15, 0) PRIMARY KEY NOT NULL,
                        ID_VISITE NUMBER(15, 0) NOT NULL,
                        SYMPTOMES NVARCHAR2(200), --маскировка
                        THERAPY NVARCHAR2(200), --маскировка
                        RESULT_DESIASE NVARCHAR2(200), --маскировка
                        CONSTRAINT FK_VISIT FOREIGN KEY (ID_VISITE) REFERENCES HEALTH(ID_VISITE)
                        ) TABLESPACE MED_CENTER;


DROP SEQUENCE USER_ID;
CREATE SEQUENCE CREATOR.USER_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

DROP SEQUENCE DOCTOR_ID;
CREATE SEQUENCE CREATOR.DOCTOR_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

--ANALYSES
DROP SEQUENCE ANALYSES_ID;
CREATE SEQUENCE CREATOR.ANALYSES_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

--WORKDAY
DROP SEQUENCE WORKDAY_ID;
CREATE SEQUENCE CREATOR.WORKDAY_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

--VISITE
DROP SEQUENCE VISITE_ID;
CREATE SEQUENCE CREATOR.VISITE_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

--DESIASE
DROP SEQUENCE DESIASE_ID;
CREATE SEQUENCE CREATOR.DESIASE_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;

--HOME_ANALYSES
DROP SEQUENCE HOME_ANALYES_ID;
CREATE SEQUENCE CREATOR.HOME_ANALYSES_ID
INCREMENT BY 1
START WITH 1
NOMAXVALUE
MINVALUE 1
NOCYCLE
NOCACHE
ORDER;