CREATE OR REPLACE DIRECTORY UTLDATA AS 'C:/Users';

CREATE OR REPLACE PROCEDURE EXPORT_DOCTOR_XML
IS
DOC DBMS_XMLDOM.DOMDocument;
XDATA XMLTYPE;
CURSOR XMLCUR IS
SELECT XMLELEMENT("DOCTORS",
XMLAttributes('http://www.w3.org/2001/XMLSchema' AS "xmlns:xsi",
'http://www.oracle.com/Users.xsd' AS "xsi:nonamespaceSchemaLocation"),
XMLAGG(XMLELEMENT("DOCTOR",
xmlelement("id_doctor", DOCTOR.ID_DOCTOR),
xmlelement("fullname", DOCTOR.FULL_NAME),
xmlelement("speciality", DOCTOR.SPECIALITY),
xmlelement("email", DOCTOR.EMAIL),
xmlelement("login", DOCTOR.LOGIN),
xmlelement("password", DOCTOR.PASSWORD)
))) from DOCTOR;

BEGIN
OPEN XMLCUR;
LOOP
FETCH XMLCUR INTO XDATA;
EXIT WHEN XMLCUR%NOTFOUND;
END LOOP;
CLOSE XMLCUR;
DOC := DBMS_XMLDOM.NewDOMDocument(XDATA);
DBMS_XMLDOM.WRITETOFILE(DOC, 'UTLDATA/import.xml');
END;

BEGIN
EXPORT_DOCTOR_XML();
END;

CREATE OR REPLACE PROCEDURE IMPORT_DOCTOR_XML
IS
RESULT_ NUMBER;
L_CLOB CLOB;
L_BFILE BFILE:= BFILENAME('UTLDATA', 'import.xml');
L_DEST_OFFSET INTEGER := 1;
L_SRC_OFFSET INTEGER := 1;
L_BFILE_CSID NUMBER := 0;
L_LANG_CONTEXT INTEGER := 0;
L_WARNING INTEGER := 0;

P DBMS_XMLPARSER.PARSER;
v_doc dbms_xmldom.domdocument;
v_root_element dbms_xmldom.domelement;
V_CHILD_NODES DBMS_XMLDOM.DOMNODELIST;
V_CURRENT_NODE DBMS_XMLDOM.DOMNODE;

ET DOCTOR%rowtype;
BEGIN

DBMS_LOB.CREATETEMPORARY (L_CLOB, TRUE);
DBMS_LOB.FILEOPEN(L_BFILE, DBMS_LOB.FILE_READONLY);

DBMS_LOB.LOADCLOBFROMFILE (DEST_LOB => L_CLOB, SRC_BFILE => L_BFILE, AMOUNT => DBMS_LOB.LOBMAXSIZE,
DEST_OFFSET => L_DEST_OFFSET, SRC_OFFSET => L_SRC_OFFSET, BFILE_CSID => L_BFILE_CSID,
LANG_CONTEXT => L_LANG_CONTEXT, WARNING => L_WARNING);
DBMS_LOB.FILECLOSE(L_BFILE);
COMMIT;
P := DBMS_XMLPARSER.NEWPARSER;
DBMS_XMLPARSER.PARSECLOB(P, L_CLOB);
V_DOC := DBMS_XMLPARSER.GETDOCUMENT(P);
V_ROOT_ELEMENT := DBMS_XMLDOM.GETDOCUMENTELEMENT(V_DOC);
V_CHILD_NODES := DBMS_XMLDOM.GETCHILDRENBYTAGNAME(V_ROOT_ELEMENT, '*');

FOR I IN 0 .. DBMS_XMLDOM.GETLENGTH(V_CHILD_NODES) - 1
LOOP
    V_CURRENT_NODE := DBMS_XMLDOM.ITEM(V_CHILD_NODES, I);
    DBMS_XSLPROCESSOR.VALUEOF(V_CURRENT_NODE, 'fullname/text()', ET.FULL_NAME);
    DBMS_XSLPROCESSOR.VALUEOF(V_CURRENT_NODE, 'speciality/text()', ET.SPECIALITY);
    DBMS_XSLPROCESSOR.VALUEOF(V_CURRENT_NODE, 'email/text()', ET.EMAIL);
    DBMS_XSLPROCESSOR.VALUEOF(V_CURRENT_NODE, 'login/text()', ET.LOGIN);
    DBMS_XSLPROCESSOR.VALUEOF(V_CURRENT_NODE, 'password/text()', ET.PASSWORD);
    
    ADMIN_PROCEDURES.INSERT_DOCTOR(ET.FULL_NAME, ET.SPECIALITY, ET.EMAIL, ET.LOGIN, ET.PASSWORD, RESULT_);
END LOOP;
DBMS_LOB.FREETEMPORARY(L_CLOB);
DBMS_XMLPARSER.FREEPARSER(P);
DBMS_XMLDOM.FREEDOCUMENT(V_DOC);
COMMIT;
END;

BEGIN
IMPORT_DOCTOR_XML();
END;

-----------------------------------------------------------------------------------------------------------------
-----------------------------------------------------------------------------------------------------------------